# Generated by Django 4.2.6 on 2024-05-29 10:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='person',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='first_appearance',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='UNKNOWN', max_length=120),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='highest_education',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='invitation_type',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='UNKNOWN', max_length=120),
        ),
        migrations.AddField(
            model_name='person',
            name='location',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='marital_status',
            field=models.CharField(max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='ministry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ministry'),
        ),
        migrations.AddField(
            model_name='person',
            name='mustard_seed',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.mustardseed'),
        ),
        migrations.AddField(
            model_name='person',
            name='other_name',
            field=models.CharField(default='UNKNOWN', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pictures'),
        ),
        migrations.AddField(
            model_name='person',
            name='telephone',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
