# Generated by Django 4.2.6 on 2024-05-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_person_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ministry',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='ministry_profile_pictures'),
        ),
        migrations.AlterField(
            model_name='mustardseed',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='mustard_profile_pictures'),
        ),
    ]
