# Generated by Django 4.2.6 on 2024-05-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_ministry_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='telephone',
            field=models.CharField(max_length=13, null=True, unique=True),
        ),
    ]
